version: "3.8"

services:
  redis:
    image: redis
    container_name: redis-limit-order
    ports:
      - 63579:6379
    volumes:
      - redis:/data

  redis-commander:
    container_name: redis-limit-order-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

  bullboard:
    container_name: limit-order-bullboard
    image: addono/bull-board
    restart: always
    ports:
      - 4500:3000
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USE_TLS: "false"
      BULL_PREFIX: bull
    # USER_LOGIN: "username"
    # USER_PASSWORD: "password"
    depends_on:
      - redis

  postgres:
    image: postgres
    container_name: local_pgdb_order
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "55436:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: super@admin.com
      PGADMIN_DEFAULT_PASSWORD: superpassword
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: 5432
      DATABASE_HOST: "postgres"
    depends_on:
      - postgres

volumes:
  redis:
    driver: local
